language: csharp
mono: none
dotnet: 2.0.0
sudo: required
dist: trusty
addons:
  apt:
    sources:
    packages:
script: 
  - echo "========== build all .Net Core samples ============"
  - dotnet restore "UA Core Library.sln"
  - dotnet restore "UA-NetStandard.sln"
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleClient
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleServer
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleClient
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleServer
  - dotnet restore "SampleApplications/Workshop/Aggregation/UA Aggregation.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet build -c Release SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet restore "SampleApplications/Workshop/Reference/UA Reference.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Reference/ConsoleReferenceServer
  - dotnet build -c Release SampleApplications/Workshop/Reference/ConsoleReferenceServer
  - echo "========== run .Net Core samples ============"
  - dotnet SampleApplications/Samples/NetCoreConsoleServer/bin/Debug/netcoreapp2.0/NetCoreConsoleServer.dll -t 10 -a

after_script:
  - echo "========== build done ============"


